#%RAML 1.0
version: v1
baseUri: https://mocksvc.mulesoft.com/mocks/e9af6216-f87b-4809-bcc7-9a8f4881a29b # 
title: customer-api

mediaType: application/json

uses:
  traits: /exchange_modules/cf176b9e-e66a-4f8e-8ac9-48aeed81f9ad/commons-traits/1.0.0/traits.raml
  customer: /exchange_modules/cf176b9e-e66a-4f8e-8ac9-48aeed81f9ad/customer-datatypes/1.0.2/customer-datatypes.raml

/customers:
  /{customerID}:
    get:
      is: [ traits.secure ]
      description: Retrieve a customer data or a 404 error if the customer doesn't exist.
      responses: 
        200:
          body:
            type: customer.Customer
            example: !include /exchange_modules/cf176b9e-e66a-4f8e-8ac9-48aeed81f9ad/customer-examples/1.0.3/existing-customer.raml
        404: