#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/81fcde13-ae94-4197-80b7-c21ed92ea51f # 
version: v2
title: customer-api

mediaType: application/json

uses:
  traits: /exchange_modules/cf176b9e-e66a-4f8e-8ac9-48aeed81f9ad/commons-traits/1.0.1/traits.raml
  customer: /exchange_modules/cf176b9e-e66a-4f8e-8ac9-48aeed81f9ad/customer-datatypes/1.0.5/customer-datatypes.raml

/customers:
  get:
    is: [ traits.secure ]
    description: Retrieve all the eisting customers.
    responses: 
      200:
        body: 
          type: customer.Customer[]
          example: !include /exchange_modules/cf176b9e-e66a-4f8e-8ac9-48aeed81f9ad/customer-examples/1.0.4/customer-list.raml
  post:
    is: [ traits.secure ]
    description: Create a new customer.
    body:
      type: customer.NewCustomer
      example: !include /exchange_modules/cf176b9e-e66a-4f8e-8ac9-48aeed81f9ad/customer-examples/1.0.4/new-customer.raml
    responses: 
        201:
          headers: 
            Content-Location:
              type: string
              example: https://mocksvc.mulesoft.com/mocks/4226505d-4d39-4fd6-ae54-b4cec3b9be9c/customer/14782369
  /{customerID}:
    get:
      is: [ traits.secure ]
      description: Retrieve a customer data or a 404 error if the customer doesn't exist.
      responses: 
        200:
          body:
            type: customer.Customer
            example: !include /exchange_modules/cf176b9e-e66a-4f8e-8ac9-48aeed81f9ad/customer-examples/1.0.4/existing-customer.raml
        404:
    patch:
      is: [ traits.secure ]
      description: Upate an existing customer.
      body:
        type: customer.Customer
        example: !include /exchange_modules/cf176b9e-e66a-4f8e-8ac9-48aeed81f9ad/customer-examples/1.0.4/existing-customer.raml
      responses: 
        204:
