#%RAML 1.0 Library

usage: To describe the phone data types

types:
  PhoneData:
    properties:
      country:
        description: the country code
        type: number
        required: false
      area:
        description: the area phone code
        type: number
        required: false
      number:
        description: the local phone number
        type: number
        required: false