customerID: 14782369
cardsPayments:
- cardPayment:
    paymentID: 12345
    cardHoldersName: TXXXXX B SXXXXXX
    cardNumber: XXXX XXXX XXXX 4163
    expirationDate:
      mounth: 00
      year: 0000
    verificationCode: 000
  billingAddress:
    country: USA
    state: FL
    city: Ponte Vedra
    street_address: 90 Fort Wade Road, Suite 200
    zip: 94108