#%RAML 1.0 NamedExample
customerID: 14782369
name: Thiago Santana
email: thiago.santana@advanceddisposal.com
phone:
  country: 1
  area: 904
  number: 7377900
serviceAddress:
  country: USA
  state: FL
  city: Ponte Vedra
  street_address: 90 Fort Wade Road, Suite 200
  zip: 94108
billingAddress:
  country: USA
  state: FL
  city: Ponte Vedra
  street_address: 90 Fort Wade Road, Suite 200
  zip: 94108
truxDB: Ponte Vedra
truxAccountID: 987654321
truxSiteID: 654321
dynamicsID: 456789