#%RAML 1.0 Library
uses:
  sa-input-values-put-type: sa-input-values-put.raml
types:
  service-agreement-put:
    properties:
      sourceInstance:
        description: where should the call land
        type: string
        required: true
      inputValues:
        description: input value variables of a service agreement
        type: sa-input-values-put-type.sa-input-values-put
        required: true